apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: llm-system
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: 'streamlit_app'
        static_configs:
          - targets: ['streamlit-service:9001']
